DexteraTech.CarStore.Web/Controllers/VersaoController.cs
using AutoMapper;
using DexteraTech.CarStore.Application.Models;
using DexteraTech.CarStore.Application.Repositorio.Interfaces;
using DexteraTech.CarStore.Web.Extensions;
using DexteraTech.CarStore.Web.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DexteraTech.CarStore.Web.Controllers;

[Authorize]
public class VersaoController : Controller
{
    public IActionResult Index()
    {
        var versaos = _versaoRespositorio.BuscarTodos();

        var versaoViewModel = _mapper.Map<List<VersaoViewModel>>(versaos);

        return View(versaoViewModel);
    }

    [HttpGet]
    [Route("/Versao/Editar/{idVersao?}")]
    public IActionResult Editar(int? idVersao)
    {
        CarregarViewBags();
        try
        {
            VersaoInputModel versaoViewModel;
            if (idVersao.HasValue && idVersao > 0)
            {
                var versao = _versaoRespositorio.ListarPorId(idVersao.Value);
                versaoViewModel = _mapper.Map<VersaoInputModel>(versao);
            }
            else
            {
                versaoViewModel = new VersaoInputModel();
            }

            return View(versaoViewModel);
        }
        catch (Exception e)
        {
            this.AddMessage(Enums.State.Error, "Registro pesquisado não existe");
            return RedirectToAction("Index");
        }

        return RedirectToAction("Index");
    }

    [HttpPost]
    public IActionResult Editar(VersaoInputModel versaoViewModel)
    {
        CarregarViewBags();
        try
        {
            if (ModelState.IsValid)
            {
                var versao = _mapper.Map<Versao>(versaoViewModel);

                if (versao.IdVersao > 0)
                    versao = _versaoRespositorio.Atualizar(versao);
                else
                    versao = _versaoRespositorio.Adicionar(versao);

                this.AddMessage(Enums.State.Success, "Versao salvo com sucesso");
                return RedirectToAction("Editar", new { versao.IdVersao });
            }

            this.AddMessage(Enums.State.Error, "Ocorreu um erro ao salvar a versão");
            return View(versaoViewModel);
        }
        catch (Exception e)
        {
            ModelState.AddModelError(e.Message, e.Message);
            return View(versaoViewModel);
        }

        return RedirectToAction("Index");
    }

    [HttpDelete]
    public IActionResult ExcluirVersao(int idVersao)
    {
        try
        {
            if (idVersao > 0)
            {
                _versaoRespositorio.Apagar(idVersao);
                return Ok("Versao excluida com sucesso");
            }
        }
        catch (Exception e)
        {
            return BadRequest("Ocorreu um erro ao excluir a versao");
        }

        return null;
    }

    private void CarregarViewBags()
    {
        ViewBag.IdModelo = _modeloRespositorio.BuscarTodos().ToSelectList("IdModelo", "NmModelo");
    }

    #region Injeção de Dependencia Repositorio e Mapper

    private readonly IVersaoRepositorio _versaoRespositorio;
    private readonly IModeloRepositorio _modeloRespositorio;
    private readonly IMarcaRepositorio _marcaRepositorio;
    private readonly ICarroceriaRepositorio _carroceriaRepositorio;
    private readonly IMapper _mapper;

    public VersaoController(IVersaoRepositorio versaoRespositorio,
        IModeloRepositorio modeloRepositorio,
        IMarcaRepositorio marcaRepositorio,
        ICarroceriaRepositorio carroceriaRepositorio,
        IMapper mapper)
    {
        _versaoRespositorio = versaoRespositorio;
        _modeloRespositorio = modeloRepositorio;
        _marcaRepositorio = marcaRepositorio;
        _carroceriaRepositorio = carroceriaRepositorio;
        _mapper = mapper;
    }

    #endregion
}

DexteraTech.CarStore.Web/Views/Versao/Editar.cshtml
@model VersaoInputModel
@{
    ViewData["Title"] = "Versão";
    ViewData["SubTitle"] = "Edição";
    ViewData["AddUrlAction"] = Url.Action("Editar", "Versao");
}

<div>

    <div class="row">
        <form asp-controller="Versao" asp-action="Editar" method="post" enctype="multipart/form-data">

            <input type="hidden" asp-for="IdVersao" />
            <div class="row">

                <div class="col">
                    <label asp-for="IdModelo" class="form-label">Modelo</label>
                    <select name="IdModelo" asp-for="IdModelo " class="form-control" asp-items="@(new SelectList(ViewBag.IdModelo, "Value", "Text"))"></select>
                    <span asp-validation-for="IdModelo" class="text-danger"></span>
                </div>
                    <div class="col">
                        <label asp-for="NmVersao" class="form-label">Versao</label>
                        <input type="text" asp-for="NmVersao" class="form-control">
                        <span asp-validation-for="NmVersao" class="text-danger"></span>
                    </div>
                </div>


            <div class="row mt-3">
                <div class="col">
                    <div class="btn-group float-end" role="group" aria-label="Basic outlined example">
                        <a class="btn btn-outline-secondary" asp-controller="Versao" asp-action="Index">Voltar </a>
                        <button type="submit" class="btn btn-success">Salvar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

DexteraTech.CarStore.Web/Views/Versao/Index.cshtml
@model List<VersaoViewModel>
@{
    ViewData["Title"] = "Versão";
    ViewData["SubTitle"] = "Listagem";
    ViewData["AddUrlAction"] = Url.Action("Editar", "Versao");
}

<body>
<div class="text-center">

    <div class="row">
        <div class="col-sm-12 align-self-center">
                                @if (Model.Any())
                    {

            <div class="table-responsive">
                <table class="table user-table">
                    <thead>
                    <tr>
                        <th scope="col">Marca</th>
                        <th scope="col">Carroceria</th>
                        <th scope="col">Modelo</th>
                        <th scope="col">Versão</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach (VersaoViewModel versao in Model)
                        {
                            <tr>
                                <td>@versao.IdModeloNavigation.IdMarcaNavigation.NmMarca</td>
                                <td>@versao.IdModeloNavigation.IdCarroceriaNavigation.NmCarroceria</td>
                                <td>@versao.IdModeloNavigation.NmModelo</td>
                                <td>@versao.NmVersao</td>
                                <td>
                                    <div class="input-group">
                                        <div class="btn-group btn-group-sm float-end" role="group">
                                            <a role="button" class="btn btn-primary" asp-route-IdVersao="@versao.IdVersao" asp-controller="Versao" asp-action="Editar" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-data-bs-title="Alterar">
                                                <i class="mdi mdi-grease-pencil"></i>
                                            </a>
                                            <a role="button" class="btn btn-danger" onclick="VersaoIndexView.excluirVersaoConfirm($(this))" data-idversao="@versao.IdVersao" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Excluir">
                                                <i class="mdi mdi-delete-forever"></i>
                                            </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
                }
                else
                {
                    <div class="alert alert-warning" role="alert">
                        Nenhuma versão cadastrada!
                    </div>
                }
        </div>
    </div>

</div>

@section Scripts {
    <script src="~/js/views/versao/index.js"></script>
    <script>
        VersaoIndexView.urlExcluirVersao = '@Url.Action("ExcluirVersao")';
    </script>
}

</body>