DexteraTech.CarStore.Web/Controllers/CambioController.cs
using AutoMapper;
using DexteraTech.CarStore.Application.Models;
using DexteraTech.CarStore.Application.Repositorio.Interfaces;
using DexteraTech.CarStore.Web.Extensions;
using DexteraTech.CarStore.Web.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DexteraTech.CarStore.Web.Controllers;

[Authorize]
public class CambioController : Controller
{
    public IActionResult Index()
    {
        var cambios = _cambioRepositorio.BuscarTodos();
        var cambioViewModel = _mapper.Map<List<CambioViewModel>>(cambios);

        return View(cambioViewModel);
    }

    [HttpGet]
    [Route("/Cambio/Editar/{idCambio?}")]
    public IActionResult Editar(int? idCambio)
    {
        try
        {
            CambioInputModel cambioViewModel;
            if (idCambio.HasValue && idCambio > 0)
            {
                var cambio = _cambioRepositorio.ListarPorId(idCambio.Value);
                cambioViewModel = _mapper.Map<CambioInputModel>(cambio);
            }
            else
            {
                cambioViewModel = new CambioInputModel();
            }

            return View(cambioViewModel);
        }
        catch (Exception e)
        {
            this.AddMessage(Enums.State.Error, "Registro pesquisado não existe");
        }

        return RedirectToAction("Index");
    }

    [HttpPost]
    public IActionResult Editar(CambioInputModel cambioViewModel)
    {
        try
        {
            if (ModelState.IsValid)
            {
                var cambio = _mapper.Map<Cambio>(cambioViewModel);

                if (cambio.IdCambio > 0)
                    cambio = _cambioRepositorio.Atualizar(cambio);
                else
                    cambio = _cambioRepositorio.Adicionar(cambio);

                this.AddMessage(Enums.State.Success, "Cambio salvo com sucesso");
                return RedirectToAction("Editar", new { cambio.IdCambio });
            }

            this.AddMessage(Enums.State.Error, "Ocorreu um erro ao salvar o cambio");
            return View(cambioViewModel);
        }
        catch (Exception e)
        {
            ModelState.AddModelError(e.Message, e.Message);
            return View(cambioViewModel);
        }
    }

    [HttpDelete]
    public IActionResult ExcluirCambio(int idCambio)
    {
        try
        {
            if (idCambio > 0)
            {
                _cambioRepositorio.Apagar(idCambio);
                return Ok("Cambio Excluido com Sucesso");
            }
        }
        catch (Exception e)
        {
            return BadRequest("Ocorreu um erro ao excluir o cambio");
        }

        return null;
    }

    #region Injeção de Dependencia Repositorio e Mapper

    private readonly ICambioRepositorio _cambioRepositorio;
    private readonly IMapper _mapper;

    public CambioController(ICambioRepositorio cambioRepositorio,
        IMapper mapper)
    {
        _cambioRepositorio = cambioRepositorio;
        _mapper = mapper;
    }

    #endregion
}

DexteraTech.CarStore.Web/Controllers/DashboardController.cs
using AutoMapper;
using DexteraTech.CarStore.Application.Repositorio.Interfaces;
using DexteraTech.CarStore.Web.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DexteraTech.CarStore.Web.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly IFotoRepositorio _fotoRepositorio;
        private readonly IMapper _mapper;
        private readonly IVeiculoRepositorio _veiculoRepositorio;
        private readonly ICambioRepositorio _cambioRepositorio;
        private readonly ICarroceriaRepositorio _carroceriaRepositorio;

        public DashboardController(IFotoRepositorio fotoRepositorio,
            IVeiculoRepositorio veiculoRepositorio,
            IMapper mapper, ICarroceriaRepositorio carroceriaRepositorio, ICambioRepositorio cambioRepositorio)
        {
            _fotoRepositorio = fotoRepositorio;
            _veiculoRepositorio = veiculoRepositorio;
            _mapper = mapper;
            _carroceriaRepositorio = carroceriaRepositorio;
            _cambioRepositorio = cambioRepositorio;
        }
        public IActionResult Index()
        {
            var dashboardViewModel = new DashboardViewModel
            {
                QtdCambios = _cambioRepositorio.BuscarTodos().Count,
                QtdCarrocerias = _carroceriaRepositorio.BuscarTodos().Count,
                QtdVeiculos = _veiculoRepositorio.BuscarTodos().Count,
                QtdVeiculosVendas = _veiculoRepositorio.BuscarTodos().Count(x => x.ExibirVitrine),
                VlrTotalVeiculos = (decimal)_veiculoRepositorio.BuscarTodos().Sum(x=> x.VlrVeiculo)
            };

            return View(dashboardViewModel);
        }
    }
}

DexteraTech.CarStore.Web/Views/Dashboard/Index.cshtml
@model DashboardViewModel
@{
    ViewData["Title"] = "Dashboard";
    ViewData["AddUrlAction"] = Url.Action("Editar", "Cambio");
}

<body>
    <div class="text-center">

        <div class="row">
            <!-- column -->
            <div class="col-sm-12 align-self-center">
                <div class="container my-4">
                    <div class="row">
                        <div class="col-md-4 mb-4">
                            <div class="card text-white bg-primary">
                                <div class="card-body">
                                    <h5 class="card-title">Carrocerias Cadastradas</h5>
                                    <p class="card-text">@Model.QtdCarrocerias</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 mb-4">
                            <div class="card text-white bg-success">
                                <div class="card-body">
                                    <h5 class="card-title">Câmbios Cadastrados</h5>
                                    <p class="card-text">@Model.QtdCambios</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 mb-4">
                            <div class="card text-white bg-info">
                                <div class="card-body">
                                    <h5 class="card-title">Veículos Cadastrados</h5>
                                    <p class="card-text">@Model.QtdVeiculos</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6 mb-4">
                            <div class="card text-white bg-warning">
                                <div class="card-body">
                                    <h5 class="card-title">Valor Total dos Veículos</h5>
                                    <p class="card-text">@Model.VlrTotalVeiculos.ToString("C02")</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6 mb-4">
                            <div class="card text-white bg-danger">
                                <div class="card-body">
                                    <h5 class="card-title">Veículos Disponíveis para Venda</h5>
                                    <p class="card-text">@Model.QtdVeiculosVendas</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    @section Scripts {
        <script src="~/js/views/Cambio/Index.js"></script>
        <script>
            CambioIndexView.urlExcluirCambio = '@Url.Action("ExcluirCambio")';
        </script>
    }

</body>