DexteraTech.CarStore.Web/Controllers/DashboardController.cs
using AutoMapper;
using DexteraTech.CarStore.Application.Repositorio.Interfaces;
using DexteraTech.CarStore.Web.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DexteraTech.CarStore.Web.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly IFotoRepositorio _fotoRepositorio;
        private readonly IMapper _mapper;
        private readonly IVeiculoRepositorio _veiculoRepositorio;
        private readonly ICambioRepositorio _cambioRepositorio;
        private readonly ICarroceriaRepositorio _carroceriaRepositorio;

        public DashboardController(IFotoRepositorio fotoRepositorio,
            IVeiculoRepositorio veiculoRepositorio,
            IMapper mapper, ICarroceriaRepositorio carroceriaRepositorio, ICambioRepositorio cambioRepositorio)
        {
            _fotoRepositorio = fotoRepositorio;
            _veiculoRepositorio = veiculoRepositorio;
            _mapper = mapper;
            _carroceriaRepositorio = carroceriaRepositorio;
            _cambioRepositorio = cambioRepositorio;
        }
        public IActionResult Index()
        {
            var dashboardViewModel = new DashboardViewModel
            {
                QtdCambios = _cambioRepositorio.BuscarTodos().Count,
                QtdCarrocerias = _carroceriaRepositorio.BuscarTodos().Count,
                QtdVeiculos = _veiculoRepositorio.BuscarTodos().Count,
                QtdVeiculosVendas = _veiculoRepositorio.BuscarTodos().Count(x => x.ExibirVitrine),
                VlrTotalVeiculos = (decimal)_veiculoRepositorio.BuscarTodos().Sum(x=> x.VlrVeiculo)
            };

            return View(dashboardViewModel);
        }
    }
}

DexteraTech.CarStore.Web/Controllers/VitrineController.cs
using AutoMapper;
using DexteraTech.CarStore.Application.Repositorio.Interfaces;
using DexteraTech.CarStore.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DexteraTech.CarStore.Web.Controllers;

[AllowAnonymous]
public class VitrineController : Controller
{
    [HttpGet]
    public IActionResult Index()
    {
        var veiculos = _veiculoRepositorio.BuscarTodoComFotosParaVenda();

        var veiculoViewModel = _mapper.Map<List<VeiculoViewModel>>(veiculos);

        return View(veiculoViewModel);
    }

    [HttpGet]
    [Route("/Vitrine/Detalhes/{IdVeiculo?}")]
    public IActionResult Detalhes(int? idVeiculo)
    {
        VeiculoViewModel veiculoViewModel;

        var veiculo = _veiculoRepositorio.ListarPorId(idVeiculo.Value);
        veiculoViewModel = _mapper.Map<VeiculoViewModel>(veiculo);
        veiculoViewModel.Fotos = _fotoRepositorio.ListarPorVeiculo(idVeiculo.Value);

        return View(veiculoViewModel);
    }

    #region Injetor de Dependencia Repositorio e Mapper

    private readonly IVeiculoRepositorio _veiculoRepositorio;
    private readonly IFotoRepositorio _fotoRepositorio;
    private readonly IMapper _mapper;

    public VitrineController(IVeiculoRepositorio veiculoRepositorio,
        IFotoRepositorio fotoRepositorio,
        IMapper mapper)
    {
        _veiculoRepositorio = veiculoRepositorio;
        _fotoRepositorio = fotoRepositorio;
        _mapper = mapper;
    }

    #endregion
}

DexteraTech.CarStore.Web/Views/Shared/_LayoutPublic.cshtml
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/img/favicon.png">
    <!-- Custom CSS -->
    <link href="~/css/style.min.css" rel="stylesheet" />

    <title>@ViewData["Title"] - TopGear</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/fontawesome.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full"
         data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <header class="topbar" data-navbarbg="skin6">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header" data-logobg="skin6">
                    <!-- ============================================================== -->
                    <!-- Logo -->
                    <!-- ============================================================== -->
                    <a class="navbar-brand ms-4" href="index.html">
                        <!-- Logo icon -->
                        <b class="logo-icon">
                            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                            <!-- Dark Logo icon -->
                            <a asp-area="" asp-controller="Home" asp-action="Index"> <img src="~/img/logoTopGear.png" style="width:130px" alt="Index" class="dark-logo" /></a>
                        </b>

                    </a>
                    <!-- ============================================================== -->
                    <!-- End Logo -->
                    <!-- ============================================================== -->
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                    <a class="nav-toggler waves-effect waves-light text-white d-block d-md-none"
                       href="javascript:void(0)">
                        <i class="ti-menu ti-close"></i>
                    </a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
                    <ul class="navbar-nav d-lg-none d-md-block ">
                        <li class="nav-item">
                            <a class="nav-toggler nav-link waves-effect waves-light text-white "
                               href="javascript:void(0)">
                                <i class="ti-menu ti-close"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav me-auto mt-md-0 ">
                        <!-- ============================================================== -->
                        <!-- Search -->
                        <!-- ============================================================== -->

                    </ul>

                    <!-- ============================================================== -->
                    <!-- Right side toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav">
                        <!-- ============================================================== -->
                        <!-- User profile and search -->
                        <!-- ============================================================== -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" asp-area="" asp-action="index" asp-controller="Dashboard" id="navbarDropdown" role="button">
                                <i class="fa-solid fa-user"></i> Entrar
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->

        <aside class="left-sidebar" data-sidebarbg="skin6">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <!-- User Profile-->

                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" asp-area="" asp-controller="Home" asp-action="Index" aria-expanded="false">
                                <i class="mdi me-2 mdi-gauge"></i><span class="hide-menu">Home</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" asp-controller="Vitrine" asp-action="index" aria-expanded="false">
                                <i class="mdi me-2 mdi-gauge"></i><span class="hide-menu">Estoque</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
            <div class="sidebar-footer">
                <div class="row">
                    <div class="col-4 link-wrap">
                        <!-- item-->
                        <a asp-area="" asp-action="index" asp-controller="Dashboard" class="link" data-bs-toggle="tooltip" title="" data-original-title="Entrar">
                            <i class="fa-solid fa-user"></i>
                        </a>
                    </div>
                    <div class="col-4 link-wrap">
                        @*  <!-- item-->
                        <a href="" class="link" data-bs-toggle="tooltip" title="" data-original-title="Email">
                        <i class="mdi mdi-gmail"></i>
                        </a>
                        *@
                    </div>
                    <div class="col-4 link-wrap">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })" class="link" data-bs-toggle="tooltip" title="" data-original-title="Logout">
                                <i class="fa-solid fa-right-from-bracket"></i>
                            </a>
                        }
                    </div>
                </div>
            </div>
        </aside>
        <div class="page-wrapper">
            <div class="page-breadcrumb">
                <div class="row align-items-center">
                    <div class="col-md-6 col-8 align-self-center">
                        <h3 class="page-title mb-0 p-0">@ViewData["Title"]</h3> 
                        @if (ViewData["SubTitle"] != null)
                        {
                            <small>@ViewData["SubTitle"]</small>
                        }
                    </div>
                    <div class="col-md-6 col-4 align-self-center">
                        <div class="text-end">
                            @if (ViewData["AddUrlAction"] != null)
                            {
                                <a class="btn btn-outline-success" href=@ViewData["AddUrlAction"]>
                                    <i class="fa fa-solid fa-plus" data-bs-toggle="tooltip" data-bs-title="Adicionar"></i>
                                </a>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <partial name="_LayoutStatePartial" />
                                @RenderBody()
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <footer class="footer">
                <div class="container">
                    &copy; 2023 - TopGear
                </div>
            </footer>
        </div>
    </div>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/app-style-switcher.js"></script>

    <!--Wave Effects -->
    <script src="~/js/waves.js"></script>

    <!--Menu sidebar -->
    <script src="~/js/sidebarmenu.js"></script>

    <!--Custom JavaScript -->
    <script src="~/js/custom.js"></script>

    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        $(document).ready(function () {
            var tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
            var tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
        });
    </script>
</body>

</html>

DexteraTech.CarStore.Web/Views/Shared/_LayoutStatePartial.cshtml
@using DexteraTech.CarStore.Web.Extensions

@if (TempData["AppMessage"] != null)
{
    var icon = "";
    var color = "";

    var message = TempData.Get<AppMessageModel>("AppMessage");
    switch (message.State)
    {
        case Enums.State.Success:
            icon = "check-circle";
            color = "success";
            break;
        case Enums.State.Information:
            icon = "info-circle";
            color = "info";
            break;
        case Enums.State.Error:
            icon = "exclamation-circle";
            color = "danger";
            break;
        default:
            throw new ArgumentOutOfRangeException();
    }

    <div class="alert alert-@color">
        <span class="fa fa-@icon"></span> @message.Message
    </div>


    TempData.Peek("AppMessage");
}